import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";

export const font = Roboto({
  subsets: ["latin"],
  weight: ["400"], // Example of multiple weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
